import { afterEach,describe,expect,it,vi } from "vitest";
import { SendService } from "../src/send-service.js";
import { fixture } from "./helpers.js";
const fixtures:ReturnType<typeof fixture>[]=[];afterEach(()=>fixtures.splice(0).forEach(x=>x.close()));
function setup(rate=5,maxMediaBytes=20*1024*1024){const f=fixture();fixtures.push(f);f.repository.upsertChat({id:"49123@s.whatsapp.net",name:"Anna"});const sender={sendText:vi.fn(async(_chatId:string,_text:string,_reply?:string)=>"wa-text"),sendMedia:vi.fn(async(_chatId:string,_media:import("../src/send-service.js").OutboundMedia,_reply?:string)=>"wa-media")};const service=new SendService(f.db,f.repository,sender,f.crypto,{sendTokenTtlSeconds:600,sendRateLimitCount:rate,sendRateLimitWindowSeconds:60,maxMediaBytes});return{...f,sender,service};}
describe("two-step sending",()=>{
  it("freezes text and sends each token once",async()=>{const{service,sender}=setup();const prepared=service.prepare("49123@s.whatsapp.net","Genauer Text");expect(sender.sendText).not.toHaveBeenCalled();expect((await service.send(prepared.send_token)).idempotent_replay).toBe(false);expect((await service.send(prepared.send_token)).idempotent_replay).toBe(true);expect(sender.sendText).toHaveBeenCalledTimes(1);});
  it("encrypts media, freezes metadata, sends once, and removes payload",async()=>{const{service,sender,db}=setup();const bytes=Buffer.from("binary image");const prepared=service.prepareMedia({chatId:"49123@s.whatsapp.net",kind:"image",dataBase64:bytes.toString("base64"),mimetype:"image/jpeg",caption:"Bildtext"});const stored=db.prepare("SELECT encrypted_payload FROM prepared_media_sends").get() as {encrypted_payload:Buffer};expect(stored.encrypted_payload.includes(bytes)).toBe(false);expect(prepared.media).toMatchObject({kind:"image",mimetype:"image/jpeg",caption:"Bildtext",bytes:bytes.length});expect(sender.sendMedia).not.toHaveBeenCalled();expect((await service.sendMedia(prepared.send_token)).idempotent_replay).toBe(false);expect((await service.sendMedia(prepared.send_token)).idempotent_replay).toBe(true);expect(sender.sendMedia).toHaveBeenCalledTimes(1);expect(sender.sendMedia.mock.calls[0]?.[1]).toMatchObject({kind:"image",mimetype:"image/jpeg",caption:"Bildtext",data:bytes});const after=db.prepare("SELECT length(encrypted_payload) AS bytes FROM prepared_media_sends").get() as {bytes:number};expect(after.bytes).toBe(0);});
  it("rejects invalid media and oversize payloads",()=>{const{service}=setup(5,4);expect(()=>service.prepareMedia({chatId:"49123@s.whatsapp.net",kind:"image",dataBase64:"not base64",mimetype:"image/jpeg"})).toThrow("base64");expect(()=>service.prepareMedia({chatId:"49123@s.whatsapp.net",kind:"image",dataBase64:Buffer.from("12345").toString("base64"),mimetype:"image/jpeg"})).toThrow("exceeds");});
  it("requires document names and rejects audio captions",()=>{const{service}=setup();const dataBase64=Buffer.from("x").toString("base64");expect(()=>service.prepareMedia({chatId:"49123@s.whatsapp.net",kind:"document",dataBase64,mimetype:"application/pdf"})).toThrow("file_name");expect(()=>service.prepareMedia({chatId:"49123@s.whatsapp.net",kind:"audio",dataBase64,mimetype:"audio/ogg",caption:"no"})).toThrow("captions");});
  it("rejects expired tokens and shares recipient rate limits",async()=>{const{service,db}=setup(1);const first=service.prepareMedia({chatId:"49123@s.whatsapp.net",kind:"document",dataBase64:Buffer.from("x").toString("base64"),mimetype:"application/pdf",fileName:"x.pdf"});await service.sendMedia(first.send_token);await expect(service.send(service.prepare("49123@s.whatsapp.net","Zwei").send_token)).rejects.toThrow("rate limit");const expired=service.prepare("49123@s.whatsapp.net","Alt");db.prepare("UPDATE prepared_sends SET expires_at=0 WHERE token_hash IS NOT NULL").run();await expect(service.send(expired.send_token)).rejects.toThrow("expired");});
});
