import { createWriteStream,existsSync,mkdirSync,readFileSync,readdirSync,renameSync,rmSync,writeFileSync } from "node:fs";
import { dirname,resolve } from "node:path";
import { once } from "node:events";
import { setTimeout as delay } from "node:timers/promises";
import { loadConfig,readSecretKey } from "./config.js";
import { openDatabase } from "./database.js";
import { CryptoBox } from "./crypto.js";
import { createLogger } from "./logger.js";
import { Repository } from "./repository.js";
import { WhatsAppService } from "./whatsapp.js";
import { clearStoredSession,createEncryptedAuthState,hasStoredSession } from "./auth-store.js";
import { AlertManager } from "./alerts.js";

const config=loadConfig(),logger=createLogger(config),command=process.argv[2],db=openDatabase(config.databasePath),crypto=new CryptoBox(readSecretKey(config.keyFile)),repository=new Repository(db,crypto),alerts=new AlertManager(config.alertWebhookUrl,logger);
try{switch(command){case"pair":await pair();break;case"status":status();break;case"purge":purge();break;case"export":await exportData();break;case"revoke":revoke();break;case"backup":await backup();break;case"restore":restore();break;default:usage();process.exitCode=2;}}catch(error){if(command==="backup")await alerts.notify("backup_failed");throw error;}finally{if(db.open)db.close();}

async function pair(){if(createEncryptedAuthState(db,crypto).state.creds.registered)throw new Error("A registered session already exists. Run revoke first only if re-pairing is intended.");const service=new WhatsAppService(repository,crypto,config,logger,true);await service.start();process.stdout.write("Scan the QR code in WhatsApp > Linked devices. Waiting up to five minutes.\n");const deadline=Date.now()+5*60_000;while(Date.now()<deadline&&service.status().state!=="connected"&&service.status().state!=="logged_out")await delay(1000);const connected=service.status().state==="connected";await service.stop();if(!connected)throw new Error("Pairing did not complete within five minutes");process.stdout.write("Pairing completed. Start the connector service now.\n");}
function status(){const chats=(db.prepare("SELECT COUNT(*) AS count FROM chats").get() as{count:number}).count,messages=(db.prepare("SELECT COUNT(*) AS count FROM messages WHERE deleted=0").get() as{count:number}).count;process.stdout.write(`${JSON.stringify({session_stored:hasStoredSession(db),last_connected_at:repository.getMetadata("last_connected_at"),last_sync_at:repository.getMetadata("last_sync_at"),chats,messages},null,2)}\n`);}
function purge(){if(!process.argv.includes("DELETE-EVERYTHING"))throw new Error("Refusing purge. Re-run with: npm run purge -- DELETE-EVERYTHING");repository.purgeAll();process.stdout.write("All connector data, messages, prepared media, audit events, and local session credentials were deleted.\n");}
function revoke(){if(!process.argv.includes("REVOKE"))throw new Error("Refusing revoke. Re-run with: npm run revoke -- REVOKE");clearStoredSession(db);process.stdout.write("Local session credentials deleted. Also remove this linked device in the WhatsApp phone app.\n");}
async function exportData(){const i=process.argv.indexOf("--output"),output=i>=0?process.argv[i+1]:undefined;if(!output)throw new Error("Usage: npm run export -- --output /secure/path/export.jsonl");mkdirSync(dirname(resolve(output)),{recursive:true,mode:0o700});const stream=createWriteStream(resolve(output),{mode:0o600});stream.write(`${JSON.stringify({type:"export_metadata",exported_at:new Date().toISOString()})}\n`);for(const row of db.prepare("SELECT jid,name,is_group,unread_count,last_message_at FROM chats ORDER BY jid").iterate())stream.write(`${JSON.stringify({type:"chat",...row as object})}\n`);for(const row of db.prepare("SELECT message_key,whatsapp_id,chat_jid,sender_jid,from_me,timestamp,text,message_type,mimetype,file_name,media_size,quoted_message_key,status FROM messages WHERE deleted=0 ORDER BY timestamp").iterate())stream.write(`${JSON.stringify({type:"message",...row as object})}\n`);stream.end();await once(stream,"finish");process.stdout.write(`Decrypted export written to ${resolve(output)}. Protect and delete it when no longer needed.\n`);}
async function backup(){const backupDir=resolve(config.dataDir,"backups");mkdirSync(backupDir,{recursive:true,mode:0o700});const stamp=new Date().toISOString().replace(/[:.]/g,"-"),plain=resolve(backupDir,`${stamp}.sqlite.tmp`),encrypted=resolve(backupDir,`${stamp}.sqlite.aesgcm`);db.pragma("wal_checkpoint(PASSIVE)");await db.backup(plain);writeFileSync(encrypted,crypto.encrypt(readFileSync(plain)),{mode:0o600});rmSync(plain,{force:true});for(const old of readdirSync(backupDir).filter(n=>n.endsWith(".sqlite.aesgcm")).sort().reverse().slice(7))rmSync(resolve(backupDir,old),{force:true});process.stdout.write(`${encrypted}\n`);}
function restore(){const source=process.argv[3];if(!source||!process.argv.includes("RESTORE"))throw new Error("Usage: stop services, then npm run restore -- /path/backup.sqlite.aesgcm RESTORE");if(!existsSync(source))throw new Error("Backup file does not exist");db.pragma("wal_checkpoint(TRUNCATE)");db.close();const restored=`${config.databasePath}.restore`;writeFileSync(restored,crypto.decrypt(readFileSync(source)),{mode:0o600});const check=openDatabase(restored),integrity=check.pragma("integrity_check",{simple:true});check.close();if(integrity!=="ok"){rmSync(restored,{force:true});throw new Error("Restored database failed integrity_check");}if(existsSync(config.databasePath))renameSync(config.databasePath,`${config.databasePath}.before-restore-${Date.now()}`);rmSync(`${config.databasePath}-wal`,{force:true});rmSync(`${config.databasePath}-shm`,{force:true});renameSync(restored,config.databasePath);process.stdout.write("Restore completed. Start the connector and verify /readyz.\n");}
function usage(){process.stderr.write("Commands: pair | status | export --output FILE | backup | restore FILE RESTORE | revoke REVOKE | purge DELETE-EVERYTHING\n");}
