import type { NextFunction,Request,Response } from "express";
import { createRemoteJWKSet,jwtVerify,type JWTPayload,type JWTVerifyGetKey } from "jose";
import type { AppConfig } from "./config.js";
export const READ_SCOPE="whatsapp:read",SEND_SCOPE="whatsapp:send";
export type AuthContext={subject:string;scopes:Set<string>;claims:JWTPayload};
declare global{namespace Express{interface Request{authContext?:AuthContext}}}
export function extractScopes(payload:JWTPayload):Set<string>{const scope=typeof payload.scope==="string"?payload.scope.split(/\s+/):[];const permissions=Array.isArray(payload.permissions)?payload.permissions.filter((x):x is string=>typeof x==="string"):[];return new Set([...scope,...permissions].filter(Boolean));}
export function createAuthMiddleware(config:AppConfig,onFailure?:()=>void){const jwks=createRemoteJWKSet(new URL(config.oauth.jwksUrl));return async(req:Request,res:Response,next:NextFunction)=>{if(config.authDisabled){req.authContext={subject:"local-development",scopes:new Set([READ_SCOPE,SEND_SCOPE]),claims:{}};next();return;}const authorization=req.header("authorization");if(!authorization?.startsWith("Bearer ")){onFailure?.();return unauthorized(res,config,"invalid_token","Missing bearer token");}try{const payload=await verifyAccessToken(authorization.slice(7),config,jwks);if(!isAllowedOwner(payload,config)){onFailure?.();return unauthorized(res,config,"invalid_token","Token owner is not allowed");}req.authContext={subject:payload.sub,scopes:extractScopes(payload),claims:payload};next();}catch{onFailure?.();return unauthorized(res,config,"invalid_token","Token validation failed");}};}
export function isAllowedOwner(payload:JWTPayload,config:AppConfig):payload is JWTPayload&{sub:string}{return Boolean(payload.sub&&config.oauth.owners.has(payload.sub));}
export async function verifyAccessToken(token:string,config:AppConfig,getKey?:JWTVerifyGetKey):Promise<JWTPayload>{const{payload}=await jwtVerify(token,getKey??createRemoteJWKSet(new URL(config.oauth.jwksUrl)),{issuer:config.oauth.issuer,audience:config.oauth.audience,algorithms:["RS256","PS256","ES256"],requiredClaims:["sub","exp"],clockTolerance:0});return payload;}
export function requireScope(auth:AuthContext|undefined,scope:string):void{if(!auth?.scopes.has(scope)){const error=new Error(`Missing OAuth scope: ${scope}`);Object.assign(error,{code:"missing_scope",status:401});throw error;}}
export function protectedResourceMetadata(config:AppConfig){return{resource:`${config.publicBaseUrl}/mcp`,authorization_servers:[config.oauth.issuer.replace(/\/$/,"")],scopes_supported:[READ_SCOPE,SEND_SCOPE],bearer_methods_supported:["header"],resource_documentation:`${config.publicBaseUrl}/docs`};}
export function challenge(config:AppConfig,error="invalid_token",description?:string):string{const parts=[`Bearer resource_metadata="${config.publicBaseUrl}/.well-known/oauth-protected-resource"`,`error="${error}"`];if(description)parts.push(`error_description="${description.replace(/["\\]/g,"")}"`);return parts.join(", ");}
function unauthorized(response:Response,config:AppConfig,error:string,description:string){response.setHeader("WWW-Authenticate",challenge(config,error,description));return response.status(401).json({error,error_description:description});}
